<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xml</string>
	</array>
	<key>name</key>
	<string>Fortify Description</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\&lt;\!\[CDATA\[)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.inline-data.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>cdata</string>
			<key>end</key>
			<string>(]]&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>code</string>
					<key>match</key>
					<string>&lt;(code)&gt;(.*?)&lt;/(code)&gt;</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.inline-data.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>bold</string>
					<key>match</key>
					<string>&lt;(b)&gt;(.*?)&lt;/(b)&gt;</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(pre)&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>pre</string>
					<key>end</key>
					<string>&lt;/(pre)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.inline-data.html</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(.*?)</string>
							<key>name</key>
							<string>variable.other.inline-data.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>description.xml.rulepack</string>
	<key>uuid</key>
	<string>17994EC8-6B1D-11D9-AC3A-000D93589AF6</string>
</dict>
</plist>
