<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nst</string>
	</array>
	<key>name</key>
	<string>Fortify NST</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>text.html.markdown.gfm meta.block-level.markdown markup.heading.markdown entity.name.section.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.html.markdown.gfm meta.block-level.markdown markup.heading.markdown entity.name.section.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.structural</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Line</string>
			<key>match</key>
			<string>(#source-(line|file|type))\s+(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>text.html.markdown.gfm meta.block-level.markdown markup.heading.markdown entity.name.section.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Line</string>
			<key>match</key>
			<string>(#NO-SOURCE-INF.*)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>class</string>
			<key>match</key>
			<string>(:)(class)(:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>null</string>
			<key>match</key>
			<string>(:)(null)(:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>(:)(abstract|annotation|anytype|boolean|break|byte|char|const|double|else|enum|environment|module|exceptions|extends|extern|false|final|float|goto|if|implements|inline|int|interface|long|NaN|native|new|null|private|protected|public|ref|remote|return|serializable|short|signed|static|strictfp|synchronized|synthetic|throw|transient|true|union|unsigned|virtual|void|volatile|while)(:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Scopes</string>
			<key>match</key>
			<string>\s(~environment|~parent~|~locals~)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sql keywords</string>
			<key>match</key>
			<string>(:)(sql:varchar|sql:varchar2|sql:number|sql:natural|sql:real|sql:date|sql:binary_integer|sql:cursor|sql:raw|sql:long raw|sql:decimal|sql:blob|sql:clob|sql:nclob|sql:bfile|sql:long|sql:nchar|sql:nvarchar2|sql:timestamp|sql:interval year|sql:interval day|sql:rowid|sql:urowid)(:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>smthg :*: smthg </string>
			<key>match</key>
			<string>\s+([^\s&lt;]+)\s+(:)(\*)(:)\s+([^\s&gt;]+)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>[ test078~module ]</string>
			<key>match</key>
			<string>(\[)\s+([^\s]+)\s+(\])</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt; str :*: &gt;</string>
			<key>match</key>
			<string>(&lt;)\s+([^\s]+)\s+(:)(\*)(:)\s+(&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt; test078~module &gt;</string>
			<key>match</key>
			<string>(&lt;)\s+([^\s]+)\s+(&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>( #0#  ~PythonGlobalsVar )</string>
			<key>match</key>
			<string>(\()\s+(#\d+#)\s+([^\s]+)\s+(\))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>operand</string>
			<key>match</key>
			<string>(:)(\.|&gt;|&lt;|!|~|==|&lt;=|&gt;=|!=|=|is|\+\+|--|\+|-|&amp;\*|\*|/|&amp;|\||\^|%|&lt;&lt;|&gt;&gt;|&gt;&gt;&gt;|`)(:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>column</string>
			<key>match</key>
			<string>(#)(\d+)(#)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>temp variables</string>
			<key>match</key>
			<string>(~t~(res~)?\d+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.single-line.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>string literal</string>
			<key>match</key>
			<string>(".*?")</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.single-line.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>string literal</string>
			<key>match</key>
			<string>('.*?')</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>burgers</string>
			<key>match</key>
			<string>(\(\))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>exceptions</string>
			<key>match</key>
			<string>(__(try|eh|catch|finally__.*)__\d+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural.nst</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function pointer call</string>
			<key>match</key>
			<string>(-(~|-)?&gt;)\s+(\()\s+(#\d+#)\s+([^\s]+)\s+(\))\s*(\()</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.nst</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.nst</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.function-call.nst</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function call</string>
			<key>match</key>
			<string>(-(~|-)?&gt;)\s+([a-zA-Z-_~0-9.]*)\s*(\()</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>special function call</string>
			<key>match</key>
			<string>~function\s+(\()</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function call end</string>
			<key>match</key>
			<string>(\))\s+;</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>colon</string>
			<key>match</key>
			<string>(\{|\}|,|:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.nst</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>brackets</string>
			<key>match</key>
			<string>(\(|\)|\[|\]|&gt;|&lt;)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nst</string>
	<key>uuid</key>
	<string>0c84615b-ed7c-4fcd-827d-8a4fde83053c</string>
</dict>
</plist>
