<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xml</string>
	</array>
	<key>name</key>
	<string>Fortify RulePack</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;(Description|Name)&gt;(\s*)?(\n*)?(\s*)?(&lt;!\[CDATA\[)?(\n*)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.cdata.xml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RulePack Description</string>
			<key>contentName</key>
			<string>constant</string>
			<key>end</key>
			<string>(\n*)?(\s*)?(\]\]&gt;)?(\s*\n*\s*)&lt;/(Description|Name)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.cdata.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(&lt;!--[A-Z]+(Rule|Transition)\s+)</string>
			<key>comment</key>
			<string>Commented Rule</string>
			<key>end</key>
			<string>(?i)(&lt;/[A-Z]+(Rule|Transition)--&gt;)</string>
			<key>name</key>
			<string>comment.rule.rulepack</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)&lt;([A-Z]+(Rule|Transition))\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Rule</string>
			<key>end</key>
			<string>(?i)&lt;/([A-Z]+(Rule|Transition))&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.xml.rule.rulepack</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Rule Attributes</string>
					<key>match</key>
					<string>(?i)(formatversion|language)(=){1}"([^\s&gt;]+)"</string>
					<key>name</key>
					<string>text.xml.formatversion.rule.rulepack</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(RuleID)&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>RuleID Tag</string>
					<key>contentName</key>
					<string>text.xml.ruleID.rule.rulepack</string>
					<key>end</key>
					<string>&lt;/(RuleID)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>&lt;(Dominant|Subordinate)&gt;</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.localname.xml meta.tag.xml</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>tags</string>
							<key>contentName</key>
							<string>text.xml.ruleID.rule.rulepack</string>
							<key>end</key>
							<string>&lt;/(Dominant|Subordinate)&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.localname.xml meta.tag.xml</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>&lt;(Pattern)&gt;</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.tag.localname.xml meta.tag.xml</string>
										</dict>
									</dict>
									<key>comment</key>
									<string>Pattern in ResultFilterRule</string>
									<key>end</key>
									<string>&lt;/(Pattern)&gt;</string>
									<key>endCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.tag.localname.xml meta.tag.xml</string>
										</dict>
									</dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>[-|]+</string>
											<key>name</key>
											<string>keyword</string>
										</dict>
										<dict>
											<key>match</key>
											<string>[a-zA-Z0-9]+</string>
											<key>name</key>
											<string>string.xml.ruleIDbit.rulepack</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>&lt;(Value)&gt;</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.tag.localname.xml meta.tag.xml</string>
										</dict>
									</dict>
									<key>comment</key>
									<string>Value tag in ResultFilterRule</string>
									<key>end</key>
									<string>&lt;/(Value)&gt;</string>
									<key>endCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.tag.localname.xml meta.tag.xml</string>
										</dict>
									</dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>[-|]+</string>
											<key>name</key>
											<string>keyword</string>
										</dict>
										<dict>
											<key>match</key>
											<string>[a-zA-Z0-9]+</string>
											<key>name</key>
											<string>string.xml.ruleIDbit.rulepack</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>[-]+</string>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-zA-Z0-9]+</string>
							<key>name</key>
							<string>string.xml.ruleIDbit.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Group)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Group</string>
					<key>end</key>
					<string>/(Group)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Group Attributes</string>
							<key>match</key>
							<string>(?i)(name)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Description)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Description</string>
					<key>end</key>
					<string>(/|Description)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Description Attributes</string>
							<key>match</key>
							<string>(?i)(ref)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Function(Call)?Identifier)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>FunctionIdentifier</string>
					<key>end</key>
					<string>(/|Function(Call)?Identifier)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>FunctionIdentifier Attributes</string>
							<key>match</key>
							<string>(?i)(id)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(ApplyTo)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ApplyTo</string>
					<key>end</key>
					<string>/(ApplyTo)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>ApplyTo Attributes</string>
							<key>match</key>
							<string>(?i)(implements|extends|overrides)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(IsType|ConstantMatches)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Conditional isType and ConstantMatches</string>
					<key>end</key>
					<string>&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Conditional subtags</string>
							<key>match</key>
							<string>(?i)(argument)(=){1}"([^\s&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Constant(Eq|Gt|Lt)|IsConstant)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Conditional subtags</string>
					<key>end</key>
					<string>/(Constant(Eq|Gt|Lt)|IsConstant)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Conditional subtags</string>
							<key>match</key>
							<string>(?i)(argument|value)(=){1}"([^\s&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Pattern)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Pattern</string>
					<key>end</key>
					<string>/(Pattern)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Pattern Attributes</string>
							<key>match</key>
							<string>(?i)(caseInsensitive)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(ValueMatch)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ValueMatch in Config Rules</string>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;/(ValueMatch)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ValueMatch in Config Rules</string>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(ValueArg)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ValueArg in Map Rules</string>
					<key>end</key>
					<string>/(ValueArg)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Value Attributes</string>
							<key>match</key>
							<string>(?i)(caseInsensitive)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(ValuesArg)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ValuesArg in Map Rules</string>
					<key>end</key>
					<string>/(ValuesArg)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Value Attributes</string>
							<key>match</key>
							<string>(?i)(caseInsensitive)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Value)/</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Empty Value</string>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Value Attributes</string>
							<key>match</key>
							<string>(?i)(caseInsensitive)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Value)[^s]</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Value with attributes</string>
					<key>end</key>
					<string>/(Value)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Value Attributes</string>
							<key>match</key>
							<string>(?i)(caseInsensitive)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(TaintFlagSet)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>TaintFlagSet</string>
					<key>end</key>
					<string>/(TaintFlagSet)?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>TaintFlagSet Attributes</string>
							<key>match</key>
							<string>(?i)(taintFlag)(=){1}"([^\s/&gt;]+)"</string>
							<key>name</key>
							<string>text.xml.attribute.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;((CallGraph)?Script)&gt;(\s*)?(\n*)?(\s*)?(&lt;!\[CDATA\[)?(\n*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>in-rule Script</string>
					<key>contentName</key>
					<string>source.js.rulepack</string>
					<key>end</key>
					<string>(\n*)?(\s*)?(\]\]&gt;)?(\s*\n*\s*)&lt;/((CallGraph)?Script)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(TaintFlags)&gt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>TaintFlags</string>
					<key>contentName</key>
					<string>text.xml.taintFlags.rule.rulepack</string>
					<key>end</key>
					<string>/(TaintFlags)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\s+,+\s+</string>
							<key>name</key>
							<string>string</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>contant</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([+-]{1})([_a-zA-Z]+)</string>
							<key>name</key>
							<string>text.xml.taintFlag.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Notes)&gt;(&lt;!\[CDATA\[)?(\n*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Notes</string>
					<key>end</key>
					<string>(\n*)?(\]\]&gt;)?&lt;/(Notes)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.xml.notes.rule.rulepack</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>text.xml.notes.rule.rulepack</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(StructuralMatch|Predicate)&gt;(\s*)?(\n*)?(\s*)?(&lt;!\[CDATA\[)?(\n*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Structural Language Blocks</string>
					<key>contentName</key>
					<string>source.structural.rulepack</string>
					<key>end</key>
					<string>(\n*)?(\s*)?(\]\]&gt;)?(\s*\n*\s*)&lt;/(StructuralMatch|Predicate)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.structural</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(Definition)&gt;(\s*)?(\n*)?(\s*)?(&lt;!\[CDATA\[)?(\n*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Definition Blocks</string>
					<key>contentName</key>
					<string>source.definition.rulepack</string>
					<key>end</key>
					<string>(\n*)?(\s*)?(\]\]&gt;)?(\s*\n*\s*)&lt;/(Definition)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.cdata.xml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.definition</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;(Script) </string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ScriptDefinition</string>
			<key>end</key>
			<string>(Script)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(formatVersion)(=){1}"([^\s&gt;]+)"\s*.*?</string>
					<key>name</key>
					<string>text.xml.attributes.script.rulepack</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(type)(=){1}([^\s&gt;]+)\s*.*?</string>
					<key>name</key>
					<string>text.xml.attributes.script.rulepack</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(name)(=){1}([^\s&gt;]+)\s*.*?</string>
					<key>name</key>
					<string>text.xml.attributes.script.rulepack</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&gt;)\n*</string>
					<key>end</key>
					<string>\n*\s*(&lt;/)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;!\[CDATA\[)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.cdata.xml</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.js.rulepack source.js</string>
							<key>end</key>
							<string>(]]&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.cdata.xml</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;(ScriptDefinitions)&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ScriptDefinitions</string>
			<key>end</key>
			<string>&lt;/(ScriptDefinitions)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml meta.tag.xml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;(Script(Definition)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ScriptDefinition</string>
					<key>end</key>
					<string>(Script(Definition)?)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.xml meta.tag.xml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i)(formatVersion)(=){1}"([^\s&gt;]+)"\s*.*?</string>
							<key>name</key>
							<string>text.xml.attributes.script.rulepack</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i)(type)(=){1}([^\s&gt;]+)\s*.*?</string>
							<key>name</key>
							<string>text.xml.attributes.script.rulepack</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i)(name)(=){1}([^\s&gt;]+)\s*.*?</string>
							<key>name</key>
							<string>text.xml.attributes.script.rulepack</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&gt;)\n*</string>
							<key>end</key>
							<string>\n*\s*(&lt;/)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(&lt;!\[CDATA\[)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>string.unquoted.cdata.xml</string>
										</dict>
									</dict>
									<key>contentName</key>
									<string>source.js.rulepack source.js</string>
									<key>end</key>
									<string>(]]&gt;)</string>
									<key>endCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>string.unquoted.cdata.xml</string>
										</dict>
									</dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>source.js</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.structural</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.structural</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.structural</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>matches|is|contains|not|and|&gt;|&lt;|!</string>
			<key>name</key>
			<string>keyword.structural</string>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.structural</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.structural</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.structural</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.rulepack</string>
	<key>uuid</key>
	<string>D0DDBCDD-3464-4B54-A6FD-A79D72759323</string>
</dict>
</plist>
