<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>structural</string>
	</array>
	<key>name</key>
	<string>Fortify Structural</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string> (matches) "</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.structural</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RegExp</string>
			<key>contentName</key>
			<string>source.regexp</string>
			<key>end</key>
			<string>"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string> matches '</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.structural</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RegExp</string>
			<key>contentName</key>
			<string>source.regexp</string>
			<key>end</key>
			<string>'</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.structural</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structural</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*([A-Za-z0-9]*):</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#doublequotedString</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#singlequotedString</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment1</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment</string>
				</dict>
			</array>
		</dict>
		<key>comment2</key>
		<dict>
			<key>match</key>
			<string>[\s]*//.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.structural</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.structural</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.structural</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\s+(!=|==|===|matches|in|is|contains|reachedBy|not|and|or|&gt;|&lt;|!)\s+</string>
			<key>name</key>
			<string>keyword.structural</string>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.structural</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.structural</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.structural</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.structural</string>
	<key>uuid</key>
	<string>0c84615b-ed7c-4fcd-827d-8a4fde83053c</string>
</dict>
</plist>
